{
  "language": "python",
  "os": [
    "linux"
  ],
  "dist": "xenial",
  "python": [
    "3.9"
  ],
  "install": [
    "pip install Django"
    "pip install Flake8"
  ],
  "script": [
    "flake8"
  ]
}